routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/datos', 'Datoscontroller@index')->name('datos');
Route::resource('datos','Datoscontroller');

app/Dato.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dato extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Datoscontroller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Dato;
class Datoscontroller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $dato = Dato::all();
        return view("datos.index",['dato' => $dato]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view("datos.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $dato = new Dato();
        $dato->nombre=$request->nombre;
        $dato->apellidop=$request->apellidop;
        $dato->apellidom=$request->apellidom;
        $dato->fechan=$request->fechan;
        
        if($dato->save()){
            return redirect("/datos");
        }
        else{
            return("datos.create");
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $dato=Dato::find($id);
        return view("datos.edit",["dato"=>$dato]);
      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $dato=Dato::find($id);
        $dato->nombre=$request->nombre;
        $dato->apellidop=$request->apellidop;
        $dato->apellidom=$request->apellidom;
        $dato->fechan=$request->fechan;
               
        if($dato->save()){
            return redirect("/datos");
        }
        else{
           return view('datos.edit',['dato'=>$dato]);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        echo"llego";
        Dato::destroy($id);
        return redirect("/datos");
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/datos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
         <div class="card">
               <div class="card-body">
                <form action="{{route('datos.store')}}" method="POST">
                  @csrf
              <div class="row justify-content-center form-group" >
                <h1>Registro de datos</h1>
              </div>
                <div class="row justify-content-center form-group">
                    <div class="col-lg-6">    
                        <input class="form-control" type="text" name="nombre" placeholder="Nombres">
                    </div>
                    <div class="col-lg-6">
                        <input class="form-control" type="text" name="apellidop" placeholder="Apellido paterno">    
                     </div>
                 <div>
                 <br>
                 <br>
             </div class="row justify-content-center form-group"  >
                   <div class="col-lg-6">
                       <input class="form-control" type="text" name="apellidom" placeholder="Apellido materno">
                  </div>
                  <div class="col-lg-6">
                       <input class="form-control" type="date" name="fechan" placeholder="Fecha de nacimiento">
                   </div>
              </div>
              <div class="row justify-content-end">
              <input class="btn btn-success" type="submit" value="Guardar"> 
              </div>
                  </form>
            </div>
    </div>
</div>
@endsection

resources/views/datos/delete.blade.php
<form action="{{url('/datos/'.$cate->id)}}" method="POST">
{{method_field('DELETE')}}
@csrf
<input type="submit" class="btn btn-link" style="color:red" value="Eliminar">
</form>

resources/views/datos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
         <div class="card">
               <div class="card-body">
                <form action="{{route('datos.update',$dato->id)}}" method="POST">
                {{method_field('PATCH')}}
                  @csrf
              <div class="row justify-content-center form-group" >
                <h1>Registro de datos</h1>
              </div>
                <div class="row justify-content-center form-group">
                    <div class="col-lg-6">    
                        <input class="form-control" type="text" value="{{$dato->nombre}}" name="nombre" placeholder="Nombres">
                    </div>
                    <div class="col-lg-6">
                        <input class="form-control" type="text" value="{{$dato->apellidop}}" name="apellidop" placeholder="Apellido paterno">    
                     </div>
                 <div>
                 <br>
                 <br>
             </div class="row justify-content-center form-group"  >
                   <div class="col-lg-6">
                       <input class="form-control" type="text"value="{{$dato->apellidom}}" name="apellidom" placeholder="Apellido materno">
                  </div>
                  <div class="col-lg-6">
                       <input class="form-control" type="date" value="{{$dato->fechan}}" name="fechan" placeholder="Fecha de nacimiento">
                   </div>
              </div>
              <div class="row justify-content-end">
              <input class="btn btn-success" type="submit" value="Guardar"> 
              </div>
            </form>
            </div>
    </div>
</div>
@endsection

resources/views/datos/index.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="card">
        <div class="card-body">
             <div class="row justify-content-center">
                 <div class="col-md-8">
                     <div class="bg-info text-white">
                          <center><h1>Datos personales</h1></center>   
                     </div>
                   <table class="table table-striped table-bordered">
                     <thead>
                          <tr>
                           <th scope="col">ID</th>
                           <th scope="col">Nombre</th>
                           <th scope="col">Apellido paterno</th>
                           <th scope="col">Apellido materno</th>
                          <th scope="col">Fecha de nacimiento</th>
                          <th scope="col"><center>Acciones</center> </th>
                          </tr>
                        </thead>
                        @foreach($dato as $cate)
                          <tr>
                          <td>{{$cate->id}}</td>
                          <td>{{$cate->nombre}}</td>
                          <td>{{$cate->apellidop}}</td>
                           <td>{{$cate->apellidom}}</td>
                           <td>{{$cate->fechan}}</td>
                           <td>
                           <div class="row">
                           <div class="col-lg-6">
                           <a href="{{url('/datos/'.$cate->id.'/edit')}}"class="btn btn-link">Editar</a>
                           </div>
                           <div class="col-lg-6">
                           @include('datos.delete',['$dato' => $cate])
                           </div>
                           </div>
                           
                       
                           </td>
                           </tr> 
                       @endforeach
                    </table>
                    <div class="row justify-content-end">
                <form action="{{route ('datos.create')}}" method="GET">
                 <input class="btn btn-info text-white" type="submit" value="Nuevo">
                 </form>
                </div>
                </div>        
            </div>
        </div> 
     </div>
</div>
    
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>